DROP PROCEDURE IF EXISTS add_columns_to_po_v10;
DELIMITER //
CREATE PROCEDURE add_columns_to_po_v10()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'purchase_orders' AND COLUMN_NAME = 'items_json') THEN
        ALTER TABLE purchase_orders ADD COLUMN items_json VARCHAR(1000);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'purchase_orders' AND COLUMN_NAME = 'quantity_json') THEN
        ALTER TABLE purchase_orders ADD COLUMN quantity_json VARCHAR(1000);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'purchase_orders' AND COLUMN_NAME = 'total_quantity') THEN
        ALTER TABLE purchase_orders ADD COLUMN total_quantity INT;
    END IF;
END //
DELIMITER ;
CALL add_columns_to_po_v10();
DROP PROCEDURE IF EXISTS add_columns_to_po_v10;
