-- Patch email_logs table to match EmailLog entity (if columns are missing)
DROP PROCEDURE IF EXISTS patch_email_logs;
DELIMITER //
CREATE PROCEDURE patch_email_logs()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'recipient') THEN
        ALTER TABLE email_logs ADD COLUMN recipient VARCHAR(150);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'subject') THEN
        ALTER TABLE email_logs ADD COLUMN subject VARCHAR(255);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'body') THEN
        ALTER TABLE email_logs ADD COLUMN body TEXT;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'status') THEN
        ALTER TABLE email_logs ADD COLUMN status VARCHAR(20);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'retry_count') THEN
        ALTER TABLE email_logs ADD COLUMN retry_count INT DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'last_attempt') THEN
        ALTER TABLE email_logs ADD COLUMN last_attempt TIMESTAMP NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'email_logs' AND COLUMN_NAME = 'error_message') THEN
        ALTER TABLE email_logs ADD COLUMN error_message TEXT;
    END IF;
END //
DELIMITER ;
CALL patch_email_logs();
DROP PROCEDURE IF EXISTS patch_email_logs;

-- Patch report_logs table to match ReportLog entity (if columns are missing)
DROP PROCEDURE IF EXISTS patch_report_logs;
DELIMITER //
CREATE PROCEDURE patch_report_logs()
BEGIN
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'report_logs' AND COLUMN_NAME = 'report_type') THEN
        ALTER TABLE report_logs ADD COLUMN report_type VARCHAR(50);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'report_logs' AND COLUMN_NAME = 'status') THEN
        ALTER TABLE report_logs ADD COLUMN status VARCHAR(20);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'report_logs' AND COLUMN_NAME = 'generated_at') THEN
        ALTER TABLE report_logs ADD COLUMN generated_at TIMESTAMP NULL;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'report_logs' AND COLUMN_NAME = 'retry_count') THEN
        ALTER TABLE report_logs ADD COLUMN retry_count INT DEFAULT 0;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'report_logs' AND COLUMN_NAME = 'error_message') THEN
        ALTER TABLE report_logs ADD COLUMN error_message TEXT;
    END IF;
END //
DELIMITER ;
CALL patch_report_logs();
DROP PROCEDURE IF EXISTS patch_report_logs;
